services:
  bitrix:
    # over configs...
    healthcheck:
      test: [ "CMD-SHELL", "php vendor/bin/console connection:healthcheck | grep OK" ]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 5s
